### ISSUE TITLE
Parser - estrarre TUTTI i dati 2018-2020

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#13]
Bisogna estrarre tutti i dati possibili, ovvero:
- i singoli candidati compresi i non-eletti ed i relativi voti
- numero di votanti (%)
- quoziente
- dati relativi al seggio

**Comment by v0lp3** [comment]
Per dati relativi al seggio intendi il numero di voti che ha preso la singola persona/lista?

**Comment by Helias** [comment]
si, in quel seggio

cioe' dobbiamo sapere il candidato X quanti voti prende ed in quale seggio, e' un dato importante
