### ISSUE TITLE
Parser - con medicina non funziona

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#14]
https://www.unict.it/sites/default/files/files/Medicina%20clinica%20e%20sperimentale(3).pdf

Inoltre, non capisco dove siano i dati ufficiali di medicina, questi "provvisori" non contengono granchè.

**Comment by Pierpaolo791** [comment]
Si trattano di dati definitivi, non hanno mai pubblicati i dati "definitivi". Bisogna considerare quelli definitivi. 

Medicina è composta da due dipartimenti: 
- Chirurgia generale e specialità medico-chirurgiche : https://www.unict.it/sites/default/files/files/Chirurgia%20generale%20e%20specialit%C3%A0%20medico%20chirurgiche(2).pdf
- Medicina clinica e sperimentale : 
https://www.unict.it/sites/default/files/files/Medicina%20clinica%20e%20sperimentale(3).pdf

https://www.unict.it/it/ateneo/risultati-provvisori-2018-dipartimenti-e-sds Qui si trova la lista di tutti i dipartimenti e relativi risultati

**Comment by Helias** [comment]
med-chirurgica non funziona bene, dà errore, ma non penso sia difficile da correggere
medclin invece funziona benissimo ;-), però dobbiamo estrarre tutti i dati da lì

Sarebbe interessante estrarre sia i valori "totali" sia quelli "per seggio", per ogni candidato

La stessa cosa andrebbe fatta per gli altri organi

**Comment by v0lp3** [comment]
> med-chirurgica non funziona bene, dà errore, ma non penso sia difficile da correggere
> medclin invece funziona benissimo ;-), però dobbiamo estrarre tutti i dati da lì
Al contrario :zany_face: , con med-chirurgica funziona, ma **i voti delle liste estratti non sono corretti**, con medclin invece da errore, ci sto lavorando.
Hai già verificato se ci sono problemi anche con altri file?

**Comment by v0lp3** [comment]
Non funziona neanche con giurisprudenza :imp:
