### ISSUE TITLE
Bug: senato 2018/2020 errore da parte del parser

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#28]
I dati di questo file non vengono estratti correttamente 
https://www.unict.it/sites/default/files/files/Senato%20accademico%202018.pdf

@Gigi-G @v0lp3 :P

**Comment by v0lp3** [comment]
Ho dato un'occhiata. Probabilmente è un bug introdotto dall'ultimo fix, nella versione precedente i dati vengono estratti correttamente.
