### ISSUE TITLE
Dati dei risultati (campione)

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#3]
Estrarre i dati dei risultati dai file PDF e convertirli in JSON (?).

Inizialmente, estrarre semplicemente dei campioni di 2 dipartimenti e di tutti gli organi superiori (di un solo anno).

Risultati anno 2018/2020 https://www.unict.it/it/ateneo/elezioni-studentesche-biennio-20182020 (i risultati provvisori, dovrebbero essere in realta' quelli definitivi)

**Comment by v0lp3** [comment]
[json.zip](https://github.com/UNICT-DMI/UNICT-Elezioni/files/5203876/json.zip)

**Comment by Helias** [comment]
Ciao, @v0lp3, ti ringrazio per questo campione, vedremo di usarlo a breve (cc @Veeenz).

Comunque @Herbrant sta lavorando ad un parser per automatizzare l'estrazione dei dati.

Ma, ti andrebbe di imparare React.js e contribuire a questo progetto? o magari ad altri progetti sotto UNICT-DMI?

**Comment by v0lp3** [comment]
Si, mi andrebbe molto (tempo permettendo). Data la diversa struttura dei file ho scritto due parser in javascript (uno per i dipartimenti e uno per gli organi superiori), probabilmente si può fare di meglio (con un solo parser). Per quanto riguarda React.js provvederò :grimacing:

**Comment by Helias** [comment]
oh :grin:, se ti piacciono le tecnologie web, sei il benveuto :wink: 
Spero di iniziare questo progetto il prima possibile, una volta iniziato, scrivero' varie issues da svolgere, come questa ma piu' relativa all'implementazione dell'applicazione che di un estrattore e magari se ti va di farne qualcuna sarai libero di assegnartela e svolgerla.

:+1:

**Comment by Herbrant** [comment]
@v0lp3 se hai già scritto un parser funzionante utilizziamo il tuo, io non ho avuto molto tempo per lavorarci! Quindi sentiti libero di fare un commit!

**Comment by Helias** [comment]
Comunque analizzando il file JSON, a noi servirebbe una struttura dati che permetta di visualizzare quanti voti ha avuto una lista e chi e' il candidato associato a quella lista, la struttura attuale non va bene, pero' sicuramente puo' aiutare nell'inizializzazione del progetto, come campione appunto :wink:

**Comment by v0lp3** [comment]
Immaginavo, ho fatto così per semplicità e perché non era stato specificato, domani vedo se riesco a sistemare :mask:

**Comment by Helias** [comment]
Hai gia' fatto tanto :grin:

**Comment by Helias** [comment]
[sample.zip](https://github.com/UNICT-DMI/UNICT-Elezioni/files/5211690/sample.zip)
