### ISSUE TITLE
Creare tabs per mostrare risultati dei vari organi

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#6]
Creare tabs con ogni pulsante per organo -> https://github.com/UNICT-DMI/UNICT-Elezioni/issues/2

Dipartimento & CdL vanno insieme, quindi bisogna creare accanto a Senato, CdA ecc. un pulsante `Dipartimento` che poi conterra' due sotto-categorie, appunto Dipartimento & CdL.

**Comment by v0lp3** [comment]
Me ne sto occupando io nel mio branch <code>test</code>

**Comment by Helias** [comment]
@v0lp3 ok 👍
