### ISSUE TITLE
Pulsante "load more" nella pagina Dipartimenti

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#77]
@drendog @Gigi-G 

Fare in modo che la pagina carichi a poco a poco i dati dei vari dipartimenti (5 alla volta magari).

**Comment by drendog** [comment]
me ne sono accorto esattamente oggi che quella pagina impiega un po' di tempo a caricare, ho giá in mente un' idea per risolvere questo problema, appena trovo un po' di tempo, proveró a risolverlo.

**Comment by Helias** [comment]
@drendog me lo ha detto qualcuno che te ne sei accorto 😁
ma penso che il problema sia il rendering istantaneo di tutti i risultati dei 19 dipartimenti

Comunque non c'è fretta, quando puoi vedi miglioralo, ma non preoccuparti

A me è venuta l'idea di caricarli a poco a poco mediante il classico pulsante "Load more" che si trova nei social, però se hai idee migliori ben venga 😁

**Comment by drendog** [comment]
@Helias si, la mia idea è quello di caricare quei dati solo una volta e passarli come parametro in quella pagina. Credo che le pagine usufruiscono del lazy loading, quindi tutti quei dati richiesti da quei require verranno caricati ogni volta che si va in quella page e potrebbero causare quel delay. Ma se il problema non si risolve in quel caso, sperando che su react esista una hook per poter gestire una component non ancora caricata, potremmo visualizzare una schermata di caricamento
