### ISSUE TITLE
Missing logos

### ISSUE THREAD

**Issue by drendog** [UNICT-DMI/UNICT-Elezioni#78]
- Nuova Ibla (Struttura didattica speciale di lingue e letterature straniere)
- Studenti per le libertà ‐ Azione universitaria (Scienze politiche e sociali)
- Crediamoci - Ares (Economia - Consigli di Corso di Laurea 2016-2018)
- Azione universitaria Ad Maiora (Scienze e tecnologie alimentari - Consigli di Corso di Laurea 2016-2018)
- Alimentazione (Scienze e tecnologie alimentari - Consigli di Corso di Laurea 2016-2018)
- Agroinformazione (Scienze e tecnologie alimentari - Consigli di Corso di Laurea 2016-2018)
- Sogno civile (Ingegneria civile e ambientale - Consigli di Corso di Laurea 2016-2018)
- Algoritmo (Ingegneria industriale - Consigli di Corso di Laurea 2016-2018)
- Libertas liberi e forti - Ares (Ingegneria industriale - Consigli di Corso di Laurea 2016-2018)
- Ebla (Lingue e culture euroamericane ed orientali - Consigli di Corso di Laurea 2016-2018)
- Nuova generazione (Lingue per la comunicazione internazionale - Consigli di Corso di Laurea 2016-2018)
- Medicamente (Medicina e chirurgia - Consigli di Corso di Laurea 2016-2018)
- Informazione (Scienze dell'educazione e della formazione - Consigli di Corso di Laurea 2016-2018) [Nessuna lista ha preso voti qui?]
- udu ‐ unione degli universitari ‐ koinè (Scienze e tecniche psicologiche - Consigli di Corso di Laurea 2016-2018)
- Alternativa (Scienze e tecniche psicologiche - Consigli di Corso di Laurea 2016-2018)
- Social (Sociologia e servizio sociale - percorso in servizi sociali - Consigli di Corso di Laurea 2016-2018)

**Comment by Helias** [comment]
:(

**Comment by Helias** [comment]
Scienze dell'educazione e della formazione  -> QUORUM non raggiunto.

loghi fixati :wink:
