### ISSUE TITLE
fix directory structure

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#79]

**Comment by drendog** [comment]
@Helias ?

**Comment by Helias** [comment]
Ci sono troppi componenti messi in disordine, troppi file messi insieme
Normalmente avrei preferito adottare la seguente struttura:
```
- ComponenteX
-- componenteX.tsx
-- componenteX.css
- ComponenteY
--  ComponenteY.tsx
-- ComponenteY.css
```

Dove X potrebbe anche richeidere Y e dove X ha SOLO X al suo interno o al massimo un piccolo componente.

ResultsTable e' enorme ed ha troppi componenti al suo interno.

So che all'inizio ResultsTable era dentro Results :sweat_smile:, infatti cerchero' in futuro di ordinarlo un po'

**Comment by drendog** [comment]
@Helias
